"""Add descricao to instrumentos

Revision ID: 178d39359bbd
Revises: f3bdf629b2a4
Create Date: 2025-11-11 16:00:58.619287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '178d39359bbd'
down_revision = 'f3bdf629b2a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questoes', schema=None) as batch_op:
        batch_op.drop_column('metadados')
        batch_op.drop_column('opcoes_resposta')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opcoes_resposta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('metadados', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
