"""Initial migration

Revision ID: 6b81f67155a4
Revises: 
Create Date: 2025-11-06 16:04:08.520391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b81f67155a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrumentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('idade_minima', sa.Integer(), nullable=False),
    sa.Column('idade_maxima', sa.Integer(), nullable=False),
    sa.Column('contexto', sa.String(length=20), nullable=False),
    sa.Column('instrucoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instrumentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instrumentos_codigo'), ['codigo'], unique=True)

    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('identificacao', sa.String(length=100), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=False),
    sa.Column('raca_etnia', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pacientes_identificacao'), ['identificacao'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nome_completo', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('avaliacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('instrumento_id', sa.Integer(), nullable=False),
    sa.Column('avaliador_id', sa.Integer(), nullable=False),
    sa.Column('data_avaliacao', sa.Date(), nullable=False),
    sa.Column('relacionamento_respondente', sa.String(length=100), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('escore_soc', sa.Integer(), nullable=True),
    sa.Column('escore_vis', sa.Integer(), nullable=True),
    sa.Column('escore_hea', sa.Integer(), nullable=True),
    sa.Column('escore_tou', sa.Integer(), nullable=True),
    sa.Column('escore_bod', sa.Integer(), nullable=True),
    sa.Column('escore_bal', sa.Integer(), nullable=True),
    sa.Column('escore_pla', sa.Integer(), nullable=True),
    sa.Column('escore_olf', sa.Integer(), nullable=True),
    sa.Column('escore_total', sa.Integer(), nullable=True),
    sa.Column('t_score_soc', sa.Integer(), nullable=True),
    sa.Column('t_score_vis', sa.Integer(), nullable=True),
    sa.Column('t_score_hea', sa.Integer(), nullable=True),
    sa.Column('t_score_tou', sa.Integer(), nullable=True),
    sa.Column('t_score_bod', sa.Integer(), nullable=True),
    sa.Column('t_score_bal', sa.Integer(), nullable=True),
    sa.Column('t_score_pla', sa.Integer(), nullable=True),
    sa.Column('t_score_olf', sa.Integer(), nullable=True),
    sa.Column('classificacao_soc', sa.String(length=50), nullable=True),
    sa.Column('classificacao_vis', sa.String(length=50), nullable=True),
    sa.Column('classificacao_hea', sa.String(length=50), nullable=True),
    sa.Column('classificacao_tou', sa.String(length=50), nullable=True),
    sa.Column('classificacao_bod', sa.String(length=50), nullable=True),
    sa.Column('classificacao_bal', sa.String(length=50), nullable=True),
    sa.Column('classificacao_pla', sa.String(length=50), nullable=True),
    sa.Column('classificacao_olf', sa.String(length=50), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['avaliador_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['instrumento_id'], ['instrumentos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('avaliacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_avaliacoes_data_avaliacao'), ['data_avaliacao'], unique=False)
        batch_op.create_index(batch_op.f('ix_avaliacoes_paciente_id'), ['paciente_id'], unique=False)

    op.create_table('dominios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrumento_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('escala_invertida', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['instrumento_id'], ['instrumentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tabelas_referencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrumento_id', sa.Integer(), nullable=False),
    sa.Column('dominio_codigo', sa.String(length=10), nullable=False),
    sa.Column('t_score', sa.Integer(), nullable=False),
    sa.Column('percentil_min', sa.Integer(), nullable=True),
    sa.Column('percentil_max', sa.Integer(), nullable=True),
    sa.Column('escore_min', sa.Integer(), nullable=False),
    sa.Column('escore_max', sa.Integer(), nullable=False),
    sa.Column('classificacao', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['instrumento_id'], ['instrumentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tabelas_referencia', schema=None) as batch_op:
        batch_op.create_index('idx_tabela_ref_lookup', ['instrumento_id', 'dominio_codigo', 't_score'], unique=False)

    op.create_table('questoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dominio_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('numero_global', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dominio_id'], ['dominios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avaliacao_id', sa.Integer(), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(length=20), nullable=False),
    sa.Column('pontuacao', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacoes.id'], ),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avaliacao_id', 'questao_id', name='uq_avaliacao_questao')
    )
    with op.batch_alter_table('respostas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_respostas_avaliacao_id'), ['avaliacao_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respostas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_respostas_avaliacao_id'))

    op.drop_table('respostas')
    op.drop_table('questoes')
    with op.batch_alter_table('tabelas_referencia', schema=None) as batch_op:
        batch_op.drop_index('idx_tabela_ref_lookup')

    op.drop_table('tabelas_referencia')
    op.drop_table('dominios')
    with op.batch_alter_table('avaliacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_avaliacoes_paciente_id'))
        batch_op.drop_index(batch_op.f('ix_avaliacoes_data_avaliacao'))

    op.drop_table('avaliacoes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pacientes_identificacao'))

    op.drop_table('pacientes')
    with op.batch_alter_table('instrumentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instrumentos_codigo'))

    op.drop_table('instrumentos')
    # ### end Alembic commands ###
