"""add criador_id to pacientes

Revision ID: e79e81ccec2b
Revises: a7b92f3c1d4e
Create Date: 2025-11-07 09:13:42.240913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79e81ccec2b'
down_revision = 'a7b92f3c1d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria_acessos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recurso_tipo', sa.String(length=50), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('data_acesso', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditoria_acessos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_acessos_data_acesso'), ['data_acesso'], unique=False)

    op.create_table('compartilhamentos_paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('compartilhou_user_id', sa.Integer(), nullable=True),
    sa.Column('recebeu_user_id', sa.Integer(), nullable=False),
    sa.Column('tipo_acesso', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_compartilhamento', sa.DateTime(), nullable=False),
    sa.Column('data_revogacao', sa.DateTime(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['compartilhou_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recebeu_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paciente_responsavel',
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tipo_vinculo', sa.String(length=20), nullable=False),
    sa.Column('data_vinculo', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('paciente_id', 'user_id')
    )
    op.create_table('anexos_avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avaliacao_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('tipo_mime', sa.String(length=100), nullable=False),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=False),
    sa.Column('tipo_anexo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_upload', sa.DateTime(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['avaliacao_id'], ['avaliacoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_arquivo')
    )
    with op.batch_alter_table('anexos_avaliacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anexos_avaliacao_avaliacao_id'), ['avaliacao_id'], unique=False)

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criador_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['criador_id'], ['id'])

    with op.batch_alter_table('plano_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plano_itens_avaliacao'))
        batch_op.drop_index(batch_op.f('ix_plano_itens_template'))
        batch_op.create_index(batch_op.f('ix_plano_itens_avaliacao_id'), ['avaliacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plano_itens_template_item_id'), ['template_item_id'], unique=False)

    with op.batch_alter_table('plano_template_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plano_template_itens_instrumento'))
        batch_op.create_index(batch_op.f('ix_plano_template_itens_instrumento_id'), ['instrumento_id'], unique=False)

    with op.batch_alter_table('prontuarios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('prontuarios_paciente_id_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prontuarios', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('prontuarios_paciente_id_key'), ['paciente_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('plano_template_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plano_template_itens_instrumento_id'))
        batch_op.create_index(batch_op.f('ix_plano_template_itens_instrumento'), ['instrumento_id'], unique=False)

    with op.batch_alter_table('plano_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plano_itens_template_item_id'))
        batch_op.drop_index(batch_op.f('ix_plano_itens_avaliacao_id'))
        batch_op.create_index(batch_op.f('ix_plano_itens_template'), ['template_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plano_itens_avaliacao'), ['avaliacao_id'], unique=False)

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('criador_id')

    with op.batch_alter_table('anexos_avaliacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anexos_avaliacao_avaliacao_id'))

    op.drop_table('anexos_avaliacao')
    op.drop_table('paciente_responsavel')
    op.drop_table('compartilhamentos_paciente')
    with op.batch_alter_table('auditoria_acessos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_acessos_data_acesso'))

    op.drop_table('auditoria_acessos')
    # ### end Alembic commands ###
